### ISSUE TITLE
console log error on app load

### ISSUE THREAD

**Issue by theunreal** [maxisam/angular2-clipboard#9]
The app works, but I get the following error in build/load:

```
client?93b6:76 [default] c:\xampp\htdocs\ImyApp\node_modules\angular2-clipboard\src\clipboard.directive.ts:2:0 
Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
```

**Comment by maxisam** [comment]
Could you setup a small example ?

**Comment by theunreal** [comment]
Not sure but I think it will happen on any app with typescript 2.0.0 and above,

see this:

"You can't use import ... = require() when targeting ES6. That's a TypeScript rule (as you can see from TS1202). You have to use import ... from '...'.

You also need to remove the extension from the module. So you should use:

import dep from './file';"

The problem is in this line:  `import Clipboard = require('clipboard');`

**Comment by maxisam** [comment]
I haven't tried Typescript 2.0 but if you test and it works on yours, do you mind to make a pull request ?

**Comment by theunreal** [comment]
I'm working locally without git, and the error appears although the application running fine and the clipboard works

**Comment by maxisam** [comment]
With 1.0.0, this issue should be fixed as well.

**Comment by theunreal** [comment]
1.0.0 still have this issue, also when updating to `commonjs`

**Comment by maxisam** [comment]
do you mind to post the tsconfig ?

**Comment by maxisam** [comment]
I just added a webpack example under demo folder. Hope it will help your issue.

**Comment by theunreal** [comment]
hey @maxisam  this is my tsconfig:

```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "li
```b": ["es6", "dom"],
    "mapRoot": "./",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}

**Comment by maxisam** [comment]
you need to add 

"types": [
       "core-js",
       "node",
       "clipboard"
     ]     

I think typeRoots is only for location, in case your node_modules is not under root. 
You also need to check if your node_modules folder  is at the location like what you set.
